app = "tempus-xmwlvg"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/tempus.db"
  ENV = "prod"

[[mounts]]
  source = "tempus_data"
  destination = "/data"
  initial_size = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 2
    hard_limit = 10

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256MB"
  cpus = 1
