version: "3"

vars:
  PROTO_DIR: ./proto
  CLIENT_DIR: ./client
  BUILD_DIR: ./bin
  GO_MODULE: github.com/Zach-Johnson/tempus

tasks:
  proto:
    desc: Generate protocol buffer code using Buf
    cmds:
      - mkdir -p {{.PROTO_DIR}}
      - buf generate

  lint:
    desc: Lint protocol buffer files
    cmds:
      - buf lint

  build:
    desc: Build the server
    deps: [proto]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/tempus-server ./main.go

  run-server:
    desc: Run the server
    deps: [build]
    env:
      RUN_MIGRATIONS: true
    cmds:
      - ./{{.BUILD_DIR}}/tempus-server

  pop-data:
    desc: Populate some data
    cmds:
      - ./data.sh

  list-tags:
    cmds:
      - "curl -s http://localhost:8080/v1/tags -H 'Content-Type: application/json' | jq "

  nuke-data:
    desc: Remove data
    cmds:
      - rm -f ./data/tempus.db
